# -*- coding: utf-8 -*-
"""AI-Powered Insights Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1APaPRsJQPhrj8at9Qf9IaPwaFTlJdXN7

Data Preparation

*   Data Loading
"""

!pip install openai

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("SampleSuperstore.csv", encoding="latin1")
df.head()

"""

*   Data Cleaning

"""

print(df.columns)

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
print(df.columns)

df.dropna(inplace=True)

df['order_date'] = pd.to_datetime(df['order_date'])

df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month

df['profit_margin'] = df['profit'] / df['sales']

print(df.groupby('region')[['sales','profit']].sum())
print(df.groupby('category')[['sales','profit']].sum())
print(df[['discount','profit']].corr())

df.to_csv("cleaned_sales_data.csv", index=False)

files.download("cleaned_sales_data.csv")

"""AI Insights Generator (GenAI)

Business Summary Generation
"""

insights = f"""
Key Insights:
- Total Sales: {df['sales'].sum():,.2f}
- Total Profit: {df['profit'].sum():,.2f}

Business Insights:
- High discounts negatively impact profit
- Some regions generate high sales but low profit
- Few categories dominate revenue

Recommendations:
- Reduce excessive discounts
- Focus on profitable regions
- Optimize product mix
"""

print(insights)

with open("ai_insights.txt", "w") as f:
    f.write(insights)